version: "3.4"

services:
    datacenter-web:
        image: princeofdukes/si_projekt_web
        ports:
            - 17179:80
        networks:
            - network
    datacenter-api:
        image: princeofdukes/si_projekt_api
        ports:
            - 17180:80
        networks:
            - network
    datacenter-generator:
        image: princeofdukes/si_projekt_generator
        ports:
            - 17181:80
        networks:
            - network
    rabbitmq:
        image: rabbitmq:3-management-alpine
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        networks:
            - network
networks:
    network: {}
